### ISSUE TITLE
error launching - ValueError: too many values to unpack

### ISSUE THREAD

**Issue by Thermionix** [ergoithz/pywinery#16]
~]$ pywinery 
	/usr/lib/python2.7/site-packages/pywinery/__init__.py:46: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
	  from gi.repository import Gtk, Gdk, GLib, Gio, GdkPixbuf, GObject
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
		"__main__", fname, loader, pkg_name)
	  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
		exec code in run_globals
	  File "/usr/lib/python2.7/site-packages/pywinery/__main__.py", line 49, in <module>
		Main().run(sys.argv)
	  File "/usr/lib/python2.7/site-packages/pywinery/__init__.py", line 1238, in __init__
		self.action_load_prefixes()
	  File "/usr/lib/python2.7/site-packages/pywinery/__init__.py", line 1191, in action_load_prefixes
		self.prefixes = list(Prefix.iter_all(self.default_prefix_config))
	  File "/usr/lib/python2.7/site-packages/pywinery/__init__.py", line 998, in iter_all
		if prefix["ww_ignore"]:
	  File "/usr/lib/python2.7/site-packages/pywinery/__init__.py", line 728, in __getitem__
		key, value = line.split("=")
	ValueError: too many values to unpack

**Comment by ergoithz** [comment]
This is a bug on wrapper.cfg. parsing, it should be fixed after https://github.com/ergoithz/pywinery/commit/98c23d99aa695bed62f30e92fa82e4164c2c9180

@Thermionix  can you test this new "hotfix" release I just made https://github.com/ergoithz/pywinery/releases/tag/0.3.3 ?
