### ISSUE TITLE
Error on start and creating a prefix

### ISSUE THREAD

**Issue by Yaksinikos** [ergoithz/pywinery#17]
```
/usr/lib/python2.7/dist-packages/pywinery/__init__.py:40: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk, Gdk, GLib, Gio, GdkPixbuf, GObject

(-c:12596): Gtk-CRITICAL **: gtk_widget_grab_default: assertion 'gtk_widget_get_can_default (widget)' failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pywinery/__init__.py", line 1868, in handle_treeview_change
    self._treeview_last_index != -2)
  File "/usr/lib/python2.7/dist-packages/pywinery/__init__.py", line 1714, in aux_handler_combo
    new_prefix.save(env=self.default_environment)
  File "/usr/lib/python2.7/dist-packages/pywinery/__init__.py", line 891, in save
    self.wine(("wineboot", "-i")) # WINE BUG WORKAROUND
  File "/usr/lib/python2.7/dist-packages/pywinery/__init__.py", line 828, in wine
    raise NoWineError
NameError: global name 'NoWineError' is not defined
```

finally prefix is not created

**Comment by Yaksinikos** [comment]
wine was not installed at all :open_mouth:
